### ISSUE TITLE
Regarding the final step, it appears that the synthesized Mid file is corrupted.

### ISSUE THREAD

**Issue by suwadaimyojin** [Code-Gale/song_conversion#1]
[](url
[d1.txt](https://github.com/Code-Gale/song_conversion/files/13497635/d1.txt)
[d2.txt](https://github.com/Code-Gale/song_conversion/files/13497636/d2.txt)

python midotrans.py
Please input the note file's name here: d1.txt
Please input the tempo file's name here: d2.txt
Enter name for output midi file: d3.mid
MIDI file generated and saved as 'output_song.mid'

Throughout the execution, I used UTF-8 encoding, and I'm not sure if it's related, but the final output Mid file is 184KB in size, yet it seems to not be functioning properly."

**Comment by Code-Gale** [comment]
it's not corrupted, just yet to get the perfected midi file based on its tempo, that's all. It's a work in progress that'll be fixed soon.
